query GetCategoryProducts(
  $facet: ID
  $page: Int = 1
  $count: Int
  $sortBy: String
  $offset: Int
  $favourites: Boolean
  $configs: [ConfigArgType]
  $filterCriteria: [filterCriteria]
  $includeRestrictions: Boolean = true
  $includeVariations: Boolean = true
  $mediaExperiments: BrowseSearchConfig
  $showDepositReturnCharge: Boolean = false
  $appliedFacetArgs: [AppliedFacetArgs]
) {
  category(
    page: $page
    count: $count
    configs: $configs
    sortBy: $sortBy
    offset: $offset
    facet: $facet
    favourites: $favourites
    config: $mediaExperiments
    filterCriteria: $filterCriteria
    appliedFacetArgs: $appliedFacetArgs
  ) {
    pageInformation: info {
      ...PageInformation
      __typename
    }
    results {
      node {
        ... on MPProduct {
          ...ProductItem
          __typename
        }
        ... on FNFProduct {
          ...ProductItem
          __typename
        }
        ... on ProductType {
          ...ProductItem
          __typename
        }
        __typename
      }
      __typename
    }
    facetLists: facetGroups {
      ...FacetLists
      __typename
    }
    facets {
      ...facet
      __typename
    }
    options {
      sortBy
      __typename
    }
    __typename
  }
}

fragment ProductItem on ProductInterface {
  typename: __typename
  ... on ProductType {
    context {
      type
      ... on ProductContextOfferType {
        linkTo
        offerType
        __typename
      }
      __typename
    }
    __typename
  }
  sellers(type: TOP, limit: 1, offset: 0) {
    ...Sellers
    __typename
  }
  ... on MPProduct {
    context {
      type
      ... on ProductContextOfferType {
        linkTo
        offerType
        __typename
      }
      __typename
    }
    seller {
      id
      name
      __typename
    }
    variations @include(if: $includeVariations) {
      ...Variation
      __typename
    }
    __typename
  }
  ... on FNFProduct {
    context {
      type
      ... on ProductContextOfferType {
        linkTo
        offerType
        __typename
      }
      __typename
    }
    variations @include(if: $includeVariations) {
      priceRange {
        minPrice
        maxPrice
        __typename
      }
      ...Variation
      __typename
    }
    __typename
  }
  id
  tpnb
  tpnc
  gtin
  adId
  baseProductId
  title
  brandName
  shortDescription
  defaultImageUrl
  superDepartmentId
  media {
    defaultImage {
      aspectRatio
      __typename
    }
    __typename
  }
  quantityInBasket
  superDepartmentName
  departmentId
  departmentName
  aisleId
  aisleName
  shelfId
  shelfName
  displayType
  productType
  charges @include(if: $showDepositReturnCharge) {
    ... on ProductDepositReturnCharge {
      __typename
      amount
    }
    __typename
  }
  averageWeight
  bulkBuyLimit
  maxQuantityAllowed: bulkBuyLimit
  groupBulkBuyLimit
  bulkBuyLimitMessage
  bulkBuyLimitGroupId
  timeRestrictedDelivery
  restrictedDelivery
  isInFavourites
  isNew
  isRestrictedOrderAmendment
  maxWeight
  minWeight
  increment
  details {
    components {
      ...Competitors
      ...AdditionalInfo
      __typename
    }
    __typename
  }
  catchWeightList {
    price
    weight
    default
    __typename
  }
  restrictions @include(if: $includeRestrictions) {
    type
    isViolated
    message
    __typename
  }
  reviews {
    stats {
      noOfReviews
      overallRating
      overallRatingRange
      __typename
    }
    __typename
  }
  modelMetadata {
    name
    version
    __typename
  }
}

fragment Competitors on CompetitorsInfo {
  competitors {
    id
    priceMatch {
      isMatching
      __typename
    }
    __typename
  }
  __typename
}

fragment AdditionalInfo on AdditionalInfo {
  isLowEverydayPricing
  __typename
}

fragment Variation on VariationsType {
  products {
    id
    baseProductId
    variationAttributes {
      attributeGroup
      attributeGroupData {
        name
        value
        attributes {
          name
          value
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}

fragment Sellers on ProductSellers {
  __typename
  results {
    id
    __typename
    isForSale
    status
    seller {
      id
      name
      logo {
        url
        __typename
      }
      __typename
    }
    price {
      price: actual
      unitPrice
      unitOfMeasure
      actual
      __typename
    }
    promotions {
      id
      promotionType
      startDate
      endDate
      description
      unitSellingInfo
      price {
        beforeDiscount
        afterDiscount
        __typename
      }
      attributes
      __typename
    }
    fulfilment(deliveryOptions: BEST) {
      __typename
      ... on ProductDeliveryType {
        end
        charges {
          value
          __typename
        }
        __typename
      }
    }
  }
}

fragment FacetLists on ProductListFacetsType {
  __typename
  category
  categoryId
  facets {
    facetId: id
    facetName: name
    binCount: count
    isSelected: selected
    __typename
  }
}

fragment PageInformation on ListInfoType {
  totalCount: total
  pageNo: page
  pageId
  count
  pageSize
  matchType
  offset
  query {
    searchTerm
    actualTerm
    __typename
  }
  __typename
}

fragment facet on FacetInterface {
  __typename
  id
  name
  type
  ... on FacetListType {
    id
    name
    listValues: values {
      name
      value
      isSelected
      count
      __typename
    }
    multiplicity
    metadata {
      description
      footerText
      linkText
      linkUrl
      __typename
    }
    __typename
  }
  ... on FacetMultiLevelType {
    id
    name
    multiLevelValues: values {
      children {
        count
        name
        value
        isSelected
        __typename
      }
      appliedValues {
        isSelected
        name
        value
        __typename
      }
      __typename
    }
    multiplicity
    metadata {
      description
      footerText
      linkText
      linkUrl
      __typename
    }
    __typename
  }
  ... on FacetBooleanType {
    booleanValues: values {
      count
      isSelected
      value
      name
      __typename
    }
    __typename
  }
}